<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3fRkvu3\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3fRkvu3/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container3fRkvu3.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container3fRkvu3\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container3fRkvu3\srcDevDebugProjectContainer(array(
    'container.build_hash' => '3fRkvu3',
    'container.build_id' => '3cf1c151',
    'container.build_time' => 1521417847,
));
